### ISSUE TITLE
非常棒的工作。

### ISSUE THREAD

**Issue by Threegood-student** [c-yn/DSANet#4]
尊敬的作者您好！Spatial Strip Attention Unit (SSA)模块当中，是先进行水平算子，然后再进行垂直算子的。想请教下您，为什么是先水平操作然后垂直操作呢？能不能先垂操作，然后水平操作呢？或者能不能设计一个双分支同时进行（分支1：先进行水平算子，然后再进行垂直算子。分支2：先进行垂直算子，然后再进行水平算子）？想请教下这几种操作之间的区别和为什么选择这样的操作顺序。谢谢！

**Comment by c-yn** [comment]
您好，邮件已回。
